In [1]:
import numpy as np

In [4]:
np.random.seed(0)
A = np.random.randint(0, 10, [2, 3])
A

array([[5, 0, 3],
       [3, 7, 9]])

## Méthodes ndarray

In [21]:
sum_all = A.sum()
sum_vertical = A.sum(axis=0) 
sum_horizontal = A.sum(axis=1)
sum_cumul = A.cumsum()
min = A.min()
max = A.max()
pos_min = A.argmin(axis=1)
pos_sort = A.argsort()
A.mean(axis=0)
std = A.std()

In [23]:
np.corrcoef(A)[0, 1] # ligne, colonne

-0.5636214801906779

In [24]:
np.unique(A, return_counts=True)

(array([0, 3, 5, 7, 9]), array([1, 2, 1, 1, 1], dtype=int64))

In [30]:
np.random.seed(0)
A = np.random.randn(5, 5)
A[0, 2] = np.nan
A[4, 3] = np.nan
np.nanmean(A)

0.5062075424895804

In [51]:
nan = np.isnan(A)

In [50]:
A[np.isnan(A)] = np.nanmean(A)

## Algèbre Linéaire

In [42]:
A = np.ones((2, 3))
B = np.ones((3, 2))

In [37]:
A.dot(B)

array([[3., 3.],
       [3., 3.]])

In [49]:
a = np.linalg.eig(A)